### ISSUE TITLE
Rewrite core

### ISSUE THREAD

**Issue by benduran** [benduran/easy-peasy-express#14]
The core is functional but sloppy. Also, the integration instructions could be clearer about how to bind the controllers to the routes.

It would also be favorable if the routes.json could also support `yaml` files, as these are much easier on the eyes.

@MCBrandenburg What do you think?

**Comment by benduran** [comment]
@MCBrandenburg I'm starting the rewrite now. The goal is to have this perform more like a traditional express middleware, rather than a standalone thing how it currently works. I'll be committing things to the `feature/new_engine` branch. Feel free to comment on them as I make progress.

**Comment by MCBrandenburg** [comment]
Looked at the commit and it looks good

**Comment by benduran** [comment]
People are still using this package, so it should probably be updated.

**Comment by benduran** [comment]
Closing Ticket as this library is deprecated and should not be used, since many alternative have been released since its original conception
